typography_spectrum: 0.40117
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#696969'
    - '#d0d0d0'
    - '#999999'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23732
analytics:
  google: null
  facebook: null
  twitter: null
name: XPACIO
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: XPACIO
description: A Better Space Trought Creativity
purpose: []
