name: XPACIO
favicon: null
layout_spectrum: 0.009008030639961362
typography_spectrum: 0.4947406800929457
title: XPACIO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#696969'
    - '#d0d0d0'
    - '#999999'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
